# FROM node:lts-alpine
# ENV NODE_ENV=production
# WORKDIR /usr/src/app
# COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "./"]
# RUN npm install --production --silent && mv node_modules ../
# COPY . .
# EXPOSE 3000
# RUN chown -R node /usr/src/app
# USER node
# CMD ["npm", "start"]


FROM node:18-alpine
WORKDIR /portfolio/
COPY public/ /portfolio/public
COPY src/ /portfolio/src
COPY package.json /portfolio/
RUN npm install
CMD ["npm", "start"]